### PR TITLE
Don't "require 'rails'" at require-time #205

### PR DESCRIPTION
**Pull request by l8nite**
This addresses issue #205 and stops figaro from explicitly requiring rails.

Here we go again

### CODE REVIEW

**Comment by l8nite** [comment]
@laserlemon any chance we can get this one merged in soon? :)

**Comment by l8nite** [comment]
@laserlemon ping? :)

**Comment by jcampos8782** [comment]
+1

**Comment by l8nite** [comment]
Pushed a tiny change that moved the `figaro/rails/application` require inside the defined? Rails check.

**Comment by hubert** [comment]
:hatched_chick: this solves a real problem for gems that are using figaro both inside and outside the context of rails.

**Comment by ak47** [comment]
+1

**Comment by l8nite** [comment]
hey @laserlemon following up on some old PRs, any chance we could get this merged and released?

**Comment by l8nite** [comment]
Closing and re-opening from my own fork because the practicefusion org fork is going to be nuked.

**Pull request closed without merging**
